"""empty message

Revision ID: 4c71b9d90c05
Revises: bbcc0e7586c7
Create Date: 2016-02-06 19:08:28.627397

"""

# revision identifiers, used by Alembic.
revision = '4c71b9d90c05'
down_revision = 'bbcc0e7586c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todo', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('todo_list', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todo_list', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_list', 'updated_at')
    op.drop_column('todo_list', 'created_at')
    op.drop_column('todo', 'updated_at')
    op.drop_column('todo', 'created_at')
    ### end Alembic commands ###
