"""empty message

Revision ID: 538dff94e64d
Revises: 4a438644e4a0
Create Date: 2016-01-03 21:46:32.440363

"""

# revision identifiers, used by Alembic.
revision = '538dff94e64d'
down_revision = '4a438644e4a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice', sa.Column('votes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice', 'votes')
    ### end Alembic commands ###
