"""empty message

Revision ID: 6dd80419ce28
Revises: bee92e82347d
Create Date: 2015-12-31 00:12:14.854751

"""

# revision identifiers, used by Alembic.
revision = '6dd80419ce28'
down_revision = 'bee92e82347d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password_hash', sa.String()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password_hash')
    ### end Alembic commands ###
