"""empty message

Revision ID: bbcc0e7586c7
Revises: 8d3b115e873d
Create Date: 2016-02-06 18:55:18.483121

"""

# revision identifiers, used by Alembic.
revision = 'bbcc0e7586c7'
down_revision = '8d3b115e873d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'todo', sa.Column('todo_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todo_list', ['todo_list_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column(u'todo', 'todo_list_id')
    op.drop_table('todo_list')
    ### end Alembic commands ###
