"""empty message

Revision ID: f6df0318c609
Revises: 538dff94e64d
Create Date: 2016-01-05 13:34:08.041513

"""

# revision identifiers, used by Alembic.
revision = 'f6df0318c609'
down_revision = '538dff94e64d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    ### end Alembic commands ###
